# docker compose yml としての書き方の バージョン
version: '3.9'

# 立てるコンテナ一覧
services:
  # アプリケーション
  app:
    # 管理コンテナ名
    container_name: ${APP_NAME}-app
    # Dockerファイルにて 定義
    build: ./docker/php
    # 場所
    volumes:
      - ./laravel-src/:/var/www/html
    # 環境設定値設定
    environment:
      # アプリ系
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL:-http://localhost:18080}
      - APP_ENV=${APP_ENV:-local}
  # メインアプリ WEBサーバー
  web:
    # 管理コンテナ名
    container_name: ${APP_NAME}-web
    # Dockerファイルにて 定義
    build: ./docker/nginx
    # 利用ポート
    ports:
      - ${WEB_PORT:-18080}:80
    # 依存関係
    depends_on:
      - app
    # 場所
    volumes:
      - ./laravel-src/:/var/www/html
    # 環境設定値
    environment:
      # nginx 対応 ホスト名(一旦コンテナごと)
      - PHP_APP_HOST=app
    # コマンド
    # defaut.conf内容書き換え
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
